// <auto-generated />
namespace TeamCatApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixTeam2Userrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixTeam2Userrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201710231546058_Fix Team2User relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
