// <auto-generated />
namespace TeamCatApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changedassignedhourtypetodouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedassignedhourtypetodouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201711150737153_Changed assigned hour type to double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
